// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcudksFZPVtfhcdEG57H0zonZo25NMapY',
    appId: '1:683813995932:web:a8bfc100cee33926193459',
    messagingSenderId: '683813995932',
    projectId: 'petproject-test-g',
    authDomain: 'petproject-test-g.firebaseapp.com',
    storageBucket: 'petproject-test-g.firebasestorage.app',
    measurementId: 'G-XLDE2ZZR3E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPnesN4MIxbJvhH-K2mwibZVC2MnQFsZ0',
    appId: '1:683813995932:android:1f426e0aabcb1721193459',
    messagingSenderId: '683813995932',
    projectId: 'petproject-test-g',
    storageBucket: 'petproject-test-g.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCieoiXq-0iu1WMFbaxnWgQA_tqvDVhZ9g',
    appId: '1:683813995932:ios:8dc947db38bd04c1193459',
    messagingSenderId: '683813995932',
    projectId: 'petproject-test-g',
    storageBucket: 'petproject-test-g.firebasestorage.app',
    androidClientId: '683813995932-7v0t55d97e6enpn3j2qa2cevcknavedf.apps.googleusercontent.com',
    iosClientId: '683813995932-fs05e13g3cboc7v0etmvammd9hotae9c.apps.googleusercontent.com',
    iosBundleId: 'com.example.petprojectTestg',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCieoiXq-0iu1WMFbaxnWgQA_tqvDVhZ9g',
    appId: '1:683813995932:ios:8dc947db38bd04c1193459',
    messagingSenderId: '683813995932',
    projectId: 'petproject-test-g',
    storageBucket: 'petproject-test-g.firebasestorage.app',
    androidClientId: '683813995932-7v0t55d97e6enpn3j2qa2cevcknavedf.apps.googleusercontent.com',
    iosClientId: '683813995932-fs05e13g3cboc7v0etmvammd9hotae9c.apps.googleusercontent.com',
    iosBundleId: 'com.example.petprojectTestg',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDcudksFZPVtfhcdEG57H0zonZo25NMapY',
    appId: '1:683813995932:web:7ba0c28acc2c57bc193459',
    messagingSenderId: '683813995932',
    projectId: 'petproject-test-g',
    authDomain: 'petproject-test-g.firebaseapp.com',
    storageBucket: 'petproject-test-g.firebasestorage.app',
    measurementId: 'G-32JRWNSJEX',
  );

}